// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: molecule.proto

package org.tripledip.dipcloud.network.protocol;

public final class MoleculeProtos {
  private MoleculeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AtomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.tripledip.dipcloud.network.protocol.Atom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional int64 sequenceNumber = 2;</code>
     */
    boolean hasSequenceNumber();
    /**
     * <code>optional int64 sequenceNumber = 2;</code>
     */
    long getSequenceNumber();

    /**
     * <code>optional string stringData = 3;</code>
     */
    boolean hasStringData();
    /**
     * <code>optional string stringData = 3;</code>
     */
    java.lang.String getStringData();
    /**
     * <code>optional string stringData = 3;</code>
     */
    com.google.protobuf.ByteString
        getStringDataBytes();

    /**
     * <code>optional int32 intData = 4;</code>
     */
    boolean hasIntData();
    /**
     * <code>optional int32 intData = 4;</code>
     */
    int getIntData();

    /**
     * <code>optional double doubleData = 5;</code>
     */
    boolean hasDoubleData();
    /**
     * <code>optional double doubleData = 5;</code>
     */
    double getDoubleData();
  }
  /**
   * Protobuf type {@code org.tripledip.dipcloud.network.protocol.Atom}
   */
  public static final class Atom extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.tripledip.dipcloud.network.protocol.Atom)
      AtomOrBuilder {
    // Use Atom.newBuilder() to construct.
    private Atom(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Atom(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Atom defaultInstance;
    public static Atom getDefaultInstance() {
      return defaultInstance;
    }

    public Atom getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Atom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequenceNumber_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              stringData_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              intData_ = input.readInt32();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              doubleData_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Atom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Atom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.class, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder.class);
    }

    public static com.google.protobuf.Parser<Atom> PARSER =
        new com.google.protobuf.AbstractParser<Atom>() {
      public Atom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Atom(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Atom> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCENUMBER_FIELD_NUMBER = 2;
    private long sequenceNumber_;
    /**
     * <code>optional int64 sequenceNumber = 2;</code>
     */
    public boolean hasSequenceNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 sequenceNumber = 2;</code>
     */
    public long getSequenceNumber() {
      return sequenceNumber_;
    }

    public static final int STRINGDATA_FIELD_NUMBER = 3;
    private java.lang.Object stringData_;
    /**
     * <code>optional string stringData = 3;</code>
     */
    public boolean hasStringData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string stringData = 3;</code>
     */
    public java.lang.String getStringData() {
      java.lang.Object ref = stringData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringData = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStringDataBytes() {
      java.lang.Object ref = stringData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTDATA_FIELD_NUMBER = 4;
    private int intData_;
    /**
     * <code>optional int32 intData = 4;</code>
     */
    public boolean hasIntData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 intData = 4;</code>
     */
    public int getIntData() {
      return intData_;
    }

    public static final int DOUBLEDATA_FIELD_NUMBER = 5;
    private double doubleData_;
    /**
     * <code>optional double doubleData = 5;</code>
     */
    public boolean hasDoubleData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double doubleData = 5;</code>
     */
    public double getDoubleData() {
      return doubleData_;
    }

    private void initFields() {
      id_ = "";
      sequenceNumber_ = 0L;
      stringData_ = "";
      intData_ = 0;
      doubleData_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStringDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, intData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, doubleData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sequenceNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStringDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, intData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, doubleData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.tripledip.dipcloud.network.protocol.Atom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.tripledip.dipcloud.network.protocol.Atom)
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Atom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Atom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.class, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder.class);
      }

      // Construct using org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sequenceNumber_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        stringData_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        intData_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleData_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Atom_descriptor;
      }

      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom getDefaultInstanceForType() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.getDefaultInstance();
      }

      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom build() {
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom buildPartial() {
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom result = new org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequenceNumber_ = sequenceNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stringData_ = stringData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.intData_ = intData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.doubleData_ = doubleData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom) {
          return mergeFrom((org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom other) {
        if (other == org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasSequenceNumber()) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.hasStringData()) {
          bitField0_ |= 0x00000004;
          stringData_ = other.stringData_;
          onChanged();
        }
        if (other.hasIntData()) {
          setIntData(other.getIntData());
        }
        if (other.hasDoubleData()) {
          setDoubleData(other.getDoubleData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private long sequenceNumber_ ;
      /**
       * <code>optional int64 sequenceNumber = 2;</code>
       */
      public boolean hasSequenceNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 sequenceNumber = 2;</code>
       */
      public long getSequenceNumber() {
        return sequenceNumber_;
      }
      /**
       * <code>optional int64 sequenceNumber = 2;</code>
       */
      public Builder setSequenceNumber(long value) {
        bitField0_ |= 0x00000002;
        sequenceNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sequenceNumber = 2;</code>
       */
      public Builder clearSequenceNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceNumber_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object stringData_ = "";
      /**
       * <code>optional string stringData = 3;</code>
       */
      public boolean hasStringData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string stringData = 3;</code>
       */
      public java.lang.String getStringData() {
        java.lang.Object ref = stringData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stringData = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringDataBytes() {
        java.lang.Object ref = stringData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringData = 3;</code>
       */
      public Builder setStringData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringData = 3;</code>
       */
      public Builder clearStringData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stringData_ = getDefaultInstance().getStringData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringData = 3;</code>
       */
      public Builder setStringDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stringData_ = value;
        onChanged();
        return this;
      }

      private int intData_ ;
      /**
       * <code>optional int32 intData = 4;</code>
       */
      public boolean hasIntData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 intData = 4;</code>
       */
      public int getIntData() {
        return intData_;
      }
      /**
       * <code>optional int32 intData = 4;</code>
       */
      public Builder setIntData(int value) {
        bitField0_ |= 0x00000008;
        intData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 intData = 4;</code>
       */
      public Builder clearIntData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        intData_ = 0;
        onChanged();
        return this;
      }

      private double doubleData_ ;
      /**
       * <code>optional double doubleData = 5;</code>
       */
      public boolean hasDoubleData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double doubleData = 5;</code>
       */
      public double getDoubleData() {
        return doubleData_;
      }
      /**
       * <code>optional double doubleData = 5;</code>
       */
      public Builder setDoubleData(double value) {
        bitField0_ |= 0x00000010;
        doubleData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double doubleData = 5;</code>
       */
      public Builder clearDoubleData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        doubleData_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.tripledip.dipcloud.network.protocol.Atom)
    }

    static {
      defaultInstance = new Atom(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.tripledip.dipcloud.network.protocol.Atom)
  }

  public interface MoleculeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.tripledip.dipcloud.network.protocol.Molecule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string channel = 1;</code>
     */
    boolean hasChannel();
    /**
     * <code>optional string channel = 1;</code>
     */
    java.lang.String getChannel();
    /**
     * <code>optional string channel = 1;</code>
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
     */
    org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction getAction();

    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    java.util.List<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom> 
        getAtomsList();
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom getAtoms(int index);
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    int getAtomsCount();
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    java.util.List<? extends org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder> 
        getAtomsOrBuilderList();
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder getAtomsOrBuilder(
        int index);

    /**
     * <code>optional string instanceId = 4;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>optional string instanceId = 4;</code>
     */
    java.lang.String getInstanceId();
    /**
     * <code>optional string instanceId = 4;</code>
     */
    com.google.protobuf.ByteString
        getInstanceIdBytes();
  }
  /**
   * Protobuf type {@code org.tripledip.dipcloud.network.protocol.Molecule}
   */
  public static final class Molecule extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.tripledip.dipcloud.network.protocol.Molecule)
      MoleculeOrBuilder {
    // Use Molecule.newBuilder() to construct.
    private Molecule(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Molecule(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Molecule defaultInstance;
    public static Molecule getDefaultInstance() {
      return defaultInstance;
    }

    public Molecule getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Molecule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              channel_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction value = org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = value;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                atoms_ = new java.util.ArrayList<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom>();
                mutable_bitField0_ |= 0x00000004;
              }
              atoms_.add(input.readMessage(org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              instanceId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          atoms_ = java.util.Collections.unmodifiableList(atoms_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Molecule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Molecule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.class, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.Builder.class);
    }

    public static com.google.protobuf.Parser<Molecule> PARSER =
        new com.google.protobuf.AbstractParser<Molecule>() {
      public Molecule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Molecule(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Molecule> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction}
     */
    public enum MoleculeAction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADD = 1;</code>
       */
      ADD(0, 1),
      /**
       * <code>UPDATE = 2;</code>
       */
      UPDATE(1, 2),
      /**
       * <code>REMOVE = 3;</code>
       */
      REMOVE(2, 3),
      /**
       * <code>SEND = 4;</code>
       */
      SEND(3, 4),
      ;

      /**
       * <code>ADD = 1;</code>
       */
      public static final int ADD_VALUE = 1;
      /**
       * <code>UPDATE = 2;</code>
       */
      public static final int UPDATE_VALUE = 2;
      /**
       * <code>REMOVE = 3;</code>
       */
      public static final int REMOVE_VALUE = 3;
      /**
       * <code>SEND = 4;</code>
       */
      public static final int SEND_VALUE = 4;


      public final int getNumber() { return value; }

      public static MoleculeAction valueOf(int value) {
        switch (value) {
          case 1: return ADD;
          case 2: return UPDATE;
          case 3: return REMOVE;
          case 4: return SEND;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MoleculeAction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MoleculeAction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MoleculeAction>() {
              public MoleculeAction findValueByNumber(int number) {
                return MoleculeAction.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.getDescriptor().getEnumTypes().get(0);
      }

      private static final MoleculeAction[] VALUES = values();

      public static MoleculeAction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MoleculeAction(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction)
    }

    private int bitField0_;
    public static final int CHANNEL_FIELD_NUMBER = 1;
    private java.lang.Object channel_;
    /**
     * <code>optional string channel = 1;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string channel = 1;</code>
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string channel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction action_;
    /**
     * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
     */
    public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction getAction() {
      return action_;
    }

    public static final int ATOMS_FIELD_NUMBER = 3;
    private java.util.List<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom> atoms_;
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    public java.util.List<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom> getAtomsList() {
      return atoms_;
    }
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    public java.util.List<? extends org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder> 
        getAtomsOrBuilderList() {
      return atoms_;
    }
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    public int getAtomsCount() {
      return atoms_.size();
    }
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom getAtoms(int index) {
      return atoms_.get(index);
    }
    /**
     * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
     */
    public org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder getAtomsOrBuilder(
        int index) {
      return atoms_.get(index);
    }

    public static final int INSTANCEID_FIELD_NUMBER = 4;
    private java.lang.Object instanceId_;
    /**
     * <code>optional string instanceId = 4;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string instanceId = 4;</code>
     */
    public java.lang.String getInstanceId() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instanceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string instanceId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceIdBytes() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      channel_ = "";
      action_ = org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction.ADD;
      atoms_ = java.util.Collections.emptyList();
      instanceId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getChannelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, action_.getNumber());
      }
      for (int i = 0; i < atoms_.size(); i++) {
        output.writeMessage(3, atoms_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getInstanceIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getChannelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_.getNumber());
      }
      for (int i = 0; i < atoms_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, atoms_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getInstanceIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.tripledip.dipcloud.network.protocol.Molecule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.tripledip.dipcloud.network.protocol.Molecule)
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.MoleculeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Molecule_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Molecule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.class, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.Builder.class);
      }

      // Construct using org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAtomsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        channel_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction.ADD;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (atomsBuilder_ == null) {
          atoms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          atomsBuilder_.clear();
        }
        instanceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.internal_static_org_tripledip_dipcloud_network_protocol_Molecule_descriptor;
      }

      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule getDefaultInstanceForType() {
        return org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.getDefaultInstance();
      }

      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule build() {
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule buildPartial() {
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule result = new org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (atomsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            atoms_ = java.util.Collections.unmodifiableList(atoms_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.atoms_ = atoms_;
        } else {
          result.atoms_ = atomsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.instanceId_ = instanceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule) {
          return mergeFrom((org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule other) {
        if (other == org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.getDefaultInstance()) return this;
        if (other.hasChannel()) {
          bitField0_ |= 0x00000001;
          channel_ = other.channel_;
          onChanged();
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (atomsBuilder_ == null) {
          if (!other.atoms_.isEmpty()) {
            if (atoms_.isEmpty()) {
              atoms_ = other.atoms_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAtomsIsMutable();
              atoms_.addAll(other.atoms_);
            }
            onChanged();
          }
        } else {
          if (!other.atoms_.isEmpty()) {
            if (atomsBuilder_.isEmpty()) {
              atomsBuilder_.dispose();
              atomsBuilder_ = null;
              atoms_ = other.atoms_;
              bitField0_ = (bitField0_ & ~0x00000004);
              atomsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAtomsFieldBuilder() : null;
            } else {
              atomsBuilder_.addAllMessages(other.atoms_);
            }
          }
        }
        if (other.hasInstanceId()) {
          bitField0_ |= 0x00000008;
          instanceId_ = other.instanceId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object channel_ = "";
      /**
       * <code>optional string channel = 1;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string channel = 1;</code>
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channel = 1;</code>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channel = 1;</code>
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 1;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 1;</code>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        channel_ = value;
        onChanged();
        return this;
      }

      private org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction action_ = org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction.ADD;
      /**
       * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
       */
      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction getAction() {
        return action_;
      }
      /**
       * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
       */
      public Builder setAction(org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.tripledip.dipcloud.network.protocol.Molecule.MoleculeAction action = 2;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = org.tripledip.dipcloud.network.protocol.MoleculeProtos.Molecule.MoleculeAction.ADD;
        onChanged();
        return this;
      }

      private java.util.List<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom> atoms_ =
        java.util.Collections.emptyList();
      private void ensureAtomsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          atoms_ = new java.util.ArrayList<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom>(atoms_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder, org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder> atomsBuilder_;

      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public java.util.List<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom> getAtomsList() {
        if (atomsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(atoms_);
        } else {
          return atomsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public int getAtomsCount() {
        if (atomsBuilder_ == null) {
          return atoms_.size();
        } else {
          return atomsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom getAtoms(int index) {
        if (atomsBuilder_ == null) {
          return atoms_.get(index);
        } else {
          return atomsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder setAtoms(
          int index, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom value) {
        if (atomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtomsIsMutable();
          atoms_.set(index, value);
          onChanged();
        } else {
          atomsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder setAtoms(
          int index, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder builderForValue) {
        if (atomsBuilder_ == null) {
          ensureAtomsIsMutable();
          atoms_.set(index, builderForValue.build());
          onChanged();
        } else {
          atomsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder addAtoms(org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom value) {
        if (atomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtomsIsMutable();
          atoms_.add(value);
          onChanged();
        } else {
          atomsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder addAtoms(
          int index, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom value) {
        if (atomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtomsIsMutable();
          atoms_.add(index, value);
          onChanged();
        } else {
          atomsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder addAtoms(
          org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder builderForValue) {
        if (atomsBuilder_ == null) {
          ensureAtomsIsMutable();
          atoms_.add(builderForValue.build());
          onChanged();
        } else {
          atomsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder addAtoms(
          int index, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder builderForValue) {
        if (atomsBuilder_ == null) {
          ensureAtomsIsMutable();
          atoms_.add(index, builderForValue.build());
          onChanged();
        } else {
          atomsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder addAllAtoms(
          java.lang.Iterable<? extends org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom> values) {
        if (atomsBuilder_ == null) {
          ensureAtomsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, atoms_);
          onChanged();
        } else {
          atomsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder clearAtoms() {
        if (atomsBuilder_ == null) {
          atoms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          atomsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public Builder removeAtoms(int index) {
        if (atomsBuilder_ == null) {
          ensureAtomsIsMutable();
          atoms_.remove(index);
          onChanged();
        } else {
          atomsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder getAtomsBuilder(
          int index) {
        return getAtomsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder getAtomsOrBuilder(
          int index) {
        if (atomsBuilder_ == null) {
          return atoms_.get(index);  } else {
          return atomsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public java.util.List<? extends org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder> 
           getAtomsOrBuilderList() {
        if (atomsBuilder_ != null) {
          return atomsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(atoms_);
        }
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder addAtomsBuilder() {
        return getAtomsFieldBuilder().addBuilder(
            org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.getDefaultInstance());
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder addAtomsBuilder(
          int index) {
        return getAtomsFieldBuilder().addBuilder(
            index, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.getDefaultInstance());
      }
      /**
       * <code>repeated .org.tripledip.dipcloud.network.protocol.Atom atoms = 3;</code>
       */
      public java.util.List<org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder> 
           getAtomsBuilderList() {
        return getAtomsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder, org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder> 
          getAtomsFieldBuilder() {
        if (atomsBuilder_ == null) {
          atomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom, org.tripledip.dipcloud.network.protocol.MoleculeProtos.Atom.Builder, org.tripledip.dipcloud.network.protocol.MoleculeProtos.AtomOrBuilder>(
                  atoms_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          atoms_ = null;
        }
        return atomsBuilder_;
      }

      private java.lang.Object instanceId_ = "";
      /**
       * <code>optional string instanceId = 4;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string instanceId = 4;</code>
       */
      public java.lang.String getInstanceId() {
        java.lang.Object ref = instanceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            instanceId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string instanceId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getInstanceIdBytes() {
        java.lang.Object ref = instanceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string instanceId = 4;</code>
       */
      public Builder setInstanceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string instanceId = 4;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        instanceId_ = getDefaultInstance().getInstanceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string instanceId = 4;</code>
       */
      public Builder setInstanceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        instanceId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.tripledip.dipcloud.network.protocol.Molecule)
    }

    static {
      defaultInstance = new Molecule(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.tripledip.dipcloud.network.protocol.Molecule)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_tripledip_dipcloud_network_protocol_Atom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_tripledip_dipcloud_network_protocol_Atom_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_tripledip_dipcloud_network_protocol_Molecule_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_tripledip_dipcloud_network_protocol_Molecule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016molecule.proto\022\'org.tripledip.dipcloud" +
      ".network.protocol\"c\n\004Atom\022\n\n\002id\030\001 \001(\t\022\026\n" +
      "\016sequenceNumber\030\002 \001(\003\022\022\n\nstringData\030\003 \001(" +
      "\t\022\017\n\007intData\030\004 \001(\005\022\022\n\ndoubleData\030\005 \001(\001\"\374" +
      "\001\n\010Molecule\022\017\n\007channel\030\001 \001(\t\022P\n\006action\030\002" +
      " \001(\0162@.org.tripledip.dipcloud.network.pr" +
      "otocol.Molecule.MoleculeAction\022<\n\005atoms\030" +
      "\003 \003(\0132-.org.tripledip.dipcloud.network.p" +
      "rotocol.Atom\022\022\n\ninstanceId\030\004 \001(\t\";\n\016Mole" +
      "culeAction\022\007\n\003ADD\020\001\022\n\n\006UPDATE\020\002\022\n\n\006REMOV",
      "E\020\003\022\010\n\004SEND\020\004B9\n\'org.tripledip.dipcloud." +
      "network.protocolB\016MoleculeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_tripledip_dipcloud_network_protocol_Atom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_tripledip_dipcloud_network_protocol_Atom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_tripledip_dipcloud_network_protocol_Atom_descriptor,
        new java.lang.String[] { "Id", "SequenceNumber", "StringData", "IntData", "DoubleData", });
    internal_static_org_tripledip_dipcloud_network_protocol_Molecule_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_tripledip_dipcloud_network_protocol_Molecule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_tripledip_dipcloud_network_protocol_Molecule_descriptor,
        new java.lang.String[] { "Channel", "Action", "Atoms", "InstanceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
